### ISSUE TITLE
Adding gutenberg (Rust static site generator)

### ISSUE THREAD

**Issue by batisteo** [eclipseo/packaging#1]
I see you’re pretty good at packaging COPR Rust programs.
Is there a way you could add https://github.com/Keats/gutenberg ?

**Comment by eclipseo** [comment]
You should ask the Fedora Rust SIG https://fedoraproject.org/wiki/SIGs/Rust to help package it. Most of the Rust package I have been working on have been integrated in Rawhide so I am not mairtening it ahymore.
